spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: mypassword # Dont you dare ever do this in a real application
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
